

CREATE DATABASE IF NOT EXISTS teamsoft;
USE teamsoft;

CREATE TABLE IF NOT EXISTS tabla_datos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(255) NOT NULL,
  numero_cuenta VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL
);

GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' IDENTIFIED BY '316170040' WITH GRANT OPTION;
FLUSH PRIVILEGES;


