

CREATE DATABASE IF NOT EXISTS teamsoft;
USE teamsoft;

CREATE TABLE IF NOT EXISTS cliente (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  nombre VARCHAR(255) NOT NULL,
  receta VARCHAR(1000) NOT NULL  
);

GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' IDENTIFIED BY '316170040' WITH GRANT OPTION;
FLUSH PRIVILEGES;


